lanche = 'Hamburgue', 'Suco', 'Pizza', 'Pudim'
print(lanche)
print(lanche[1])
print(lanche[-2])
print(lanche[1:3])
print(lanche[:2])
print(lanche[1].replace('Suco', 'Refrigerante'))
lanche2 = lanche[1].replace('Suco', 'Refrigerante')
print(lanche2)
print(sorted(lanche))
print(lanche)